### ISSUE TITLE
Merge `GOSTrocks` into `GOSTraster`

### ISSUE THREAD

**Issue by g4brielvs** [worldbank/GOSTnetsraster#11]
Per #10, this issue is for merging [gostrocks](https://github.com/bpstewar/gostrocks) into this project.

**Comment by elbeejay** [comment]
@andresfchamorro do you have any preference for which project merges into which, or whether a new repository should be started and we pull the code from `gostrocks` and `GOSTNets_Raster` into a new one? 

I'm not sure what's best as `gostrocks` already exists as a package but isn't in the `worldbank` project space, while `GOSTNets_Raster` hasn't been packaged and exists under the `worldbank` group, but naming-wise doesn't fit the planned conventions.
