### ISSUE TITLE
 TypeError: generate_feature_vectors() missing 1 required positional argument: 'featIdx'

### ISSUE THREAD

**Issue by ajuang** [worldbank/GOSTnetsraster#3]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-32-3979d0653a42>](https://localhost:8080/#) in <module>()
      1 drive_time_thresholds = [60, 120, 180, 240] # minutes
----> 2 drive_vectors = ma.generate_feature_vectors(inR, mcp, inD, drive_time_thresholds)
      3 drive_vectors.to_file(os.path.join('/content/drive/Shareddrives/Applied Data Science/Engagements/Stanford Community Health Resilience Project/Travel Time/drive_vectors.shp'))

TypeError: generate_feature_vectors() missing 1 required positional argument: 'featIdx'

I am getting this error when trying to generate drive time vectors

**Comment by chapmanjacobd** [comment]
In the function documentation they say they are using tempID for default but they don't set featIdx as a kwarg.

https://github.com/worldbank/GOSTNets_Raster/blob/ec96520b3d4e7d7f4b2c8d0a17016d696af3d100/src/GOSTNetsRaster/market_access.py#L168

so you'll need to add the name of the column like this:

```
drive_vectors = ma.generate_feature_vectors(inR, mcp, inD, drive_time_thresholds, 'tempID')
```
